In [55]:
import os
import numpy as np
os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID" 
os.environ["CUDA_VISIBLE_DEVICES"] = "3" 

In [56]:
with open("../datasets/AAPD/llm_cluster_result/zero_shot_text_test1.json","r") as json_file:
    json_list = list(json_file)

In [57]:
predict_output = []
for i in range(len(json_list)):
    predict_output.append(json_list[i].split('"labels": [')[1].split(',')[0][1:-1])

In [58]:
file1 = open('../datasets/AAPD/true_labels.txt', 'r')
summary = file1.readlines()  

In [59]:
label_dic = {}
for row in summary:
    label_dic[row.split('; ')[0]] = row.split('; ')[1]

In [60]:
file2 = open('../datasets/AAPD/label_test.txt', 'r')
org_true_label = file2.readlines()
true_label = []
for row in org_true_label:
    short_label = row.strip().split(' ')
    long_label = []
    for index in short_label:
        long_label.append(label_dic[index])
    true_label.append(long_label)
true_label

[['Computer Vision and Pattern Recognition', 'Machine Learning'],
 ['Information Theory', 'Information Theory'],
 ['Artificial Intelligence', 'Data Structures and Algorithms'],
 ['Combinatorics', 'Discrete Mathematics', 'Probability'],
 ['Information Theory',
  'Networking and Internet Architecture',
  'Information Theory',
  'Probability'],
 ['Computer Vision and Pattern Recognition',
  'Information Theory',
  'Information Theory'],
 ['Information Theory', 'Information Theory'],
 ['Computer Science and Game Theory', 'Networking and Internet Architecture'],
 ['Computers and Society', 'Logic in Computer Science'],
 ['Machine Learning', 'Social and Information Networks', 'Machine Learning'],
 ['Combinatorics', 'Discrete Mathematics'],
 ['Information Theory', 'Information Theory'],
 ['Data Structures and Algorithms', 'Computational Geometry'],
 ['Computation and Language;\n', 'Computation and Language'],
 ['Information Theory',
  'Artificial Intelligence',
  'Machine Learning',
  'Informa

In [61]:
from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2', device = 0)


In [62]:
correct = 0
for index in range(len(predict_output)):
    query_embedding = model.encode(predict_output[index])
    print(predict_output[index], true_label[index])
    passage_embedding = model.encode(true_label[index])
    sim_scores = util.dot_score(query_embedding, passage_embedding)[0].numpy()
    print(sim_scores)
    rank_list = np.argsort(sim_scores)[-1]
    if sim_scores[rank_list] >= 0.60:
        correct +=1
correct

Computer Vision ['Computer Vision and Pattern Recognition', 'Machine Learning']
[0.7780858 0.5183859]
Optimization Problems in Communication Networks ['Information Theory', 'Information Theory']
[0.33844742 0.33844745]
Multi-Agent Systems ['Artificial Intelligence', 'Data Structures and Algorithms']
[0.4243873  0.22103155]
Scientific Inquiry ['Combinatorics', 'Discrete Mathematics', 'Probability']
[0.20314917 0.192951   0.1881992 ]
Wireless Communications ['Information Theory', 'Networking and Internet Architecture', 'Information Theory', 'Probability']
[0.35326254 0.41110715 0.35326254 0.08893187]
Optimization ['Computer Vision and Pattern Recognition', 'Information Theory', 'Information Theory']
[0.28733635 0.28889236 0.28889236]
Wiretap Channel and Lattice Coset Encoding ['Information Theory', 'Information Theory']
[0.27901918 0.27901918]
Scientific Inquiry ['Computer Science and Game Theory', 'Networking and Internet Architecture']
[0.23837295 0.09878353]
Text Mining and Visualizat

212

In [24]:
ground_truth = []
for row in summary:
    ground_truth.append(row.split('; ')[1])

In [26]:
file1 = open('../datasets/AAPD/llm_cluster_result/update_labelspace.txt', 'r')
documents = file1.readlines()  

label_space = []
for row in documents:
    label = row.strip()
    label_space.append(label)

In [27]:
correct = 0
for lb in ground_truth:
    query_embedding = model.encode(lb)
    print(lb)
    passage_embedding = model.encode(label_space)
    sim_scores = util.dot_score(query_embedding, passage_embedding)[0].numpy()
    rank_list = np.argsort(sim_scores)[-1]
    print(label_space[rank_list], sim_scores[rank_list])
    if sim_scores[rank_list] >= 0.60:
        correct +=1
correct

Information Retrieval
Information Retrieval 1.0
Methodology
Theoretical Computer Science 0.418443
Quantum Physics

Quantum Computing 0.7059134
Information Theory
Information Theory 0.99999994
Information Theory
Information Theory 0.99999994
Applications
Computer Science 0.4330575
Computer Vision and Pattern Recognition
Computer Vision 0.77808595
Computation and Language
Computational Complexity 0.5707912
Artificial Intelligence
Robotics and Artificial Intelligence 0.76883245
Numerical Analysis
Optimization 0.44985604
Mathematical Software
Theoretical Computer Science 0.43425134
Cryptography and Security
Cryptography 0.8977585
Software Engineering
Computer Science 0.65342367
Machine Learning
Machine Learning 1.0
Networking and Internet Architecture
Communication Systems and Networks 0.58830416
Systems and Control
Control Systems 0.92395794
Data Structures and Algorithms
Graph Algorithms 0.5896046
Computational Complexity
Computational Complexity 1.0
Formal Languages and Automata Theory


28

In [28]:
correct/ len(ground_truth)

0.5185185185185185

In [29]:
with open("../datasets/Reuters-21578/llm_cluster_result/zero_shot_text_test.json","r") as json_file:
    json_list = list(json_file)

In [37]:
predict_output = []
for i in range(len(json_list)):
    predict_output.append(json_list[i].split('"labels": [')[1].split(',')[0][1:-1])

In [33]:
file1 = open('../datasets/Reuters-21578/test_label.txt', 'r')
labels = file1.readlines()[:1000]  
test_set = []  
for label in labels:
    lbs = label.strip().split(' ')
    test_set.append(lbs)

In [35]:
file1 = open('../datasets/Reuters-21578/test_label.txt', 'r')
labels = file1.readlines()
true_labels = []
for row in labels:
    lb_set = row.strip().split(' ')
    for lb in lb_set:
        if not lb in true_labels:
            true_labels.append(lb)
len(true_labels)

90

In [38]:
correct = 0
for index in range(len(predict_output)):
    query_embedding = model.encode(predict_output[index])
    print(predict_output[index], test_set[index])
    passage_embedding = model.encode(test_set[index])
    sim_scores = util.dot_score(query_embedding, passage_embedding)[0].numpy()
    print(sim_scores)
    rank_list = np.argsort(sim_scores)[-1]
    if sim_scores[rank_list] >= 0.60:
        correct +=1

trade_surplus ['trade']
[0.4621315]
agriculture ['grain']
[0.4831558]
natural gas ['nat-gas', 'crude']
[0.7379503 0.4206357]
economic growth ['rubber', 'tin', 'sugar', 'corn', 'rice', 'grain', 'trade']
[0.17631824 0.09895086 0.08952741 0.15540086 0.13683201 0.09335928
 0.17316827]
palm oil ['palm-oil', 'veg-oil']
[0.96469706 0.5938508 ]
shipping ['ship']
[0.71062666]
rubber ['rubber', 'coffee', 'lumber', 'palm-oil', 'veg-oil']
[1.0000001  0.25706416 0.35786444 0.3771101  0.35498777]
agriculture ['wheat', 'grain']
[0.5528396  0.48315582]
mining ['gold']
[0.41335472]
banking ['acq']
[0.24160089]
mining ['tin']
[0.35684258]
monetary policy ['interest', 'money-fx']
[0.43026766 0.53972757]
financial losses ['copper', 'acq']
[0.19947402 0.1341422 ]
economic growth ['ipi']
[0.18460433]
agriculture ['soybean', 'oilseed', 'corn', 'grain', 'carcass', 'livestock', 'rice', 'trade']
[0.4630654  0.46096462 0.5442389  0.48315588 0.3825903  0.6434237
 0.49478465 0.22720541]
stock listings ['earn']
[0.

[0.71062666]
rubber ['earn']
[0.16108401]
labour_disputes ['ship']
[0.16964543]
financial statements ['earn']
[0.27848294]
earnings ['earn']
[0.6168959]
financial statements ['earn']
[0.27848294]
banking ['interest', 'money-fx']
[0.4702595  0.49652755]
earnings ['earn']
[0.6168959]
financial statements ['earn']
[0.27848294]
financial statements ['earn']
[0.27848294]
financial statements ['earn']
[0.27848294]
financial statements ['earn']
[0.27848294]
earnings ['earn']
[0.6168959]
unemployment ['jobs']
[0.565886]
sales ['earn']
[0.40866196]
sales ['acq']
[0.2674072]
financial statements ['earn']
[0.27848294]
regulation ['acq']
[0.20294166]
financial statements ['earn']
[0.27848294]
banking ['earn']
[0.38772967]
financial statements ['earn']
[0.27848294]
sales ['sugar']
[0.28651288]
economic policy ['money-fx']
[0.36491323]
sales ['sugar']
[0.28651288]
financial statements ['earn']
[0.27848294]
earnings ['earn']
[0.6168959]
financial statements ['earn']
[0.27848294]
sales ['earn']
[0.408

In [52]:
file1 = open('../datasets/Amazon-531/llm_cluster_result/update_labelspace.txt', 'r')
documents = file1.readlines()  

label_space = []
for row in documents:
    label = row.strip()
    label_space.append(label)

In [53]:
correct = 0
for lb in true_labels:
    query_embedding = model.encode(lb)
    print(lb)
    passage_embedding = model.encode(label_space)
    sim_scores = util.dot_score(query_embedding, passage_embedding)[0].numpy()
    rank_list = np.argsort(sim_scores)[-1]
    print(label_space[rank_list], sim_scores[rank_list])
    if sim_scores[rank_list] >= 0.60:
        correct +=1
correct

grocery_gourmet_food
shopping_grocery 0.691828
meat_poultry
food_ingredients 0.5403876
jerky
snacks 0.4030494
toys_games
toys_games 0.9999999
games
games 1.0
puzzles
toys_puzzles 0.679267
jigsaw_puzzles
toys_puzzles 0.667863
board_games
board_games 0.99999994
beverages
food_beverages 0.81020904
juices
food_beverages 0.5057407
beauty
beauty 1.0
makeup
beauty_makeup 0.7922852
nails
beauty_nail_care 0.6575123
arts_crafts
toys_crafts 0.8020563
drawing_painting_supplies
crafting_supplies 0.6362072
action_toy_figures
toys_action_figures 0.9660249
figures
toys_action_figures 0.53402567
dolls_accessories
toys_dolls 0.8014587
dolls
toys_dolls 0.7617769
card_games
board_games 0.7792025
drawing_sketching_tablets
technology_gadgets 0.37693655
baby_toddler_toys
parenting_toys 0.7736389
shape_sorters
shopping_beauty 0.31531602
health_personal_care
health_personal_care 1.0
personal_care
health_personal_care 0.855265
deodorants_antiperspirants
personal_care_deodorants 0.79440784
nutrition_wellness
hea

203

In [44]:
file2 = open('../datasets/Amazon-531/test_label.txt', 'r')
test_label_set = file2.readlines()[:1000]
test_set = []  
for label in test_label_set:
    labels = label.strip().split(', ')
    test_set.append(labels)
len(test_set)

1000

In [47]:
file2 = open('../datasets/Amazon-531/test/labels.txt', 'r')
test_label_set = file2.readlines()
true_labels = []
for label in test_label_set:
    true_labels.append(label.strip().split('\t')[1])
true_labels

['grocery_gourmet_food',
 'meat_poultry',
 'jerky',
 'toys_games',
 'games',
 'puzzles',
 'jigsaw_puzzles',
 'board_games',
 'beverages',
 'juices',
 'beauty',
 'makeup',
 'nails',
 'arts_crafts',
 'drawing_painting_supplies',
 'action_toy_figures',
 'figures',
 'dolls_accessories',
 'dolls',
 'card_games',
 'drawing_sketching_tablets',
 'baby_toddler_toys',
 'shape_sorters',
 'health_personal_care',
 'personal_care',
 'deodorants_antiperspirants',
 'nutrition_wellness',
 'nutrition_bars_drinks',
 'learning_education',
 'habitats',
 'electronics_for_kids',
 'household_supplies',
 'household_batteries',
 'push_pull_toys',
 'stuffed_animals_plush',
 'tricycles',
 'scooters_wagons',
 'clay_dough',
 'health_care',
 'allergy',
 'baby_products',
 'gear',
 'baby_gyms_playmats',
 'shaving_hair_removal',
 'skin_care',
 'face',
 'animals_figures',
 'feminine_care',
 'music_sound',
 'oral_hygiene',
 'grown_up_toys',
 'dress_up_pretend_play',
 'pretend_play',
 'novelty_gag_toys',
 'bath_body',
 'c

In [48]:
with open("../datasets/Amazon-531/llm_cluster_result/zero_shot_text_test.json","r") as json_file:
    json_list = list(json_file)

In [49]:
predict_output = []
for i in range(len(json_list)):
    predict_output.append(json_list[i].split('"labels": [')[1].split(',')[0][1:-1])

In [50]:
correct = 0
for index in range(len(predict_output)):
    query_embedding = model.encode(predict_output[index])
    print(predict_output[index], test_set[index])
    passage_embedding = model.encode(test_set[index])
    sim_scores = util.dot_score(query_embedding, passage_embedding)[0].numpy()
    print(sim_scores)
    rank_list = np.argsort(sim_scores)[-1]
    if sim_scores[rank_list] >= 0.60:
        correct +=1

beauty_hair_care ['beauty', 'hair_care', 'styling_tools,']
[0.56852764 0.8634659  0.32811424]
toys_gifts ['toys_games', 'dolls_accessories', 'dolls,']
[0.8262298 0.6618003 0.5062856]
home_and_garden_sleep_technology ['baby_products', 'gifts,']
[0.25850987 0.15093413]
recipes ['grocery_gourmet_food', 'pantry_staples', 'canned_jarred_food,']
[0.43134737 0.32638174 0.43596968]
beauty_products ['beauty', 'skin_care', 'sun,']
[0.6002429  0.5132369  0.22619517]
recommendations ['grocery_gourmet_food', 'beverages', 'tea,']
[0.19348939 0.25644177 0.26208317]
beauty_products ['beauty', 'skin_care', 'body,']
[0.6002429  0.5132369  0.36049676]
toys_gifts ['baby_products', 'gear', 'baby_gyms_playmats,']
[0.57862127 0.38300684 0.5084454 ]
oral_health ['health_personal_care', 'personal_care', 'oral_hygiene,']
[0.49894044 0.3455468  0.8151215 ]
family_kids_toys ['toys_games', 'dress_up_pretend_play', 'pretend_play,']
[0.7044606  0.30757248 0.30223352]
beauty_products ['health_personal_care', 'persona

In [54]:
203/531

0.3822975517890772

In [2]:
file2 = open('../datasets/Reuters-21578/test_raw_texts.txt', 'r')
docs = file2.readlines()[:1000]

In [21]:
top_labels = []
for doc in docs[:10]:
    query_embedding = model.encode(doc)
    passage_embedding = model.encode(label_space)
    sim_scores = util.dot_score(query_embedding, passage_embedding)[0].numpy()
    rank_list = np.argsort(sim_scores)[-8:]
    exp_label = []
    for index in rank_list:
        exp_label.append(label_space[index])
    top_labels.append(exp_label)
top_labels

[['Trade Surplus',
  'Oil Trade',
  'Trade Legislation',
  'Soybean Exports',
  'Trade Deficit',
  'Exports',
  'Trade Policy',
  'International Trade'],
 ['Sugar Production and Exports',
  'Beef Exports',
  'Inventory',
  'Commodity Prices',
  'Commodities',
  'Wheat Harvest',
  'Agriculture',
  'Agricultural Products'],
 ['Soybean Exports',
  'Oil and Gas',
  'Monetary Policy',
  'Oil Prices',
  'Economic Priorities',
  'Commodity Prices',
  'Economic Outlook',
  'Economic Forecast'],
 ['Sales Growth',
  'Trade Surplus',
  'International Trade',
  'Beef Exports',
  'Sugar Production and Exports',
  'Exports',
  'Trade Deficit',
  'Soybean Exports'],
 ['Sugar Production and Exports',
  'International Trade',
  'Soybean Exports',
  'Exports',
  'Oil Trade',
  'Commodity Prices',
  "Venezuela's Oil Exports and Refinery Investments",
  'Oil Prices'],
 ['Shipping',
  'International Trade',
  'Discontinued Operations',
  'Trade Policy',
  'Labor Disputes',
  'Trade Legislation',
  'Ferry D